In [1]:
# String
c = 'hello'
print(type(c))

<class 'str'>


In [2]:
# Integer
a = 1
print(type(a))

<class 'int'>


In [3]:
# Float
b = 1.0
print(type(b))

<class 'float'>


In [4]:
# Boolean
d = True
print(type(d))

<class 'bool'>


In [5]:
# None
e = None
print(type(e))

<class 'NoneType'>


In [6]:
# Cast integer to string
print(type(str(a)))

<class 'str'>


In [7]:
# Assigning and combining strings
a = 'Hello'
b = 'World'
print(a + ' ' + b)

Hello World


In [8]:
# f-strings
firstname = 'Shawn'
print(f'My name is {firstname}')

My name is Shawn


In [9]:
# Combining f-strings
firstname = 'Shawn'
lastname = 'Rhoads'

print(f'My name is {firstname} {lastname}')

My name is Shawn Rhoads


In [10]:
# Repeat String without spaces
print(str(a)*5)

HelloHelloHelloHelloHello


In [11]:
# Repeat String with spaces
print(str(a+' ')*5)

Hello Hello Hello Hello Hello 


In [12]:
# Addition
a = 2 + 7
print(f'a = {a}')

a = 9


In [13]:
# Subtraction
b = a - 5
print(f'b = a-5 = {a}-5 = {b}')

b = a-5 = 9-5 = 4


In [14]:
# Multiplication
print(f'b*2 = {b}*2 = {b*2}')

b*2 = 4*2 = 8


In [15]:
# Division
print(f'a/3 = {a}/3 = {a/3}')

a/3 = 9/3 = 3.0


In [16]:
# Exponentiation
print(f'b^2 = b**2 = {b}**2 = {b**2}')

b^2 = b**2 = 4**2 = 16


In [17]:
# Modulo 
print('(Modulo returns the remainder of dividing the left hand operand by right hand operand)')
print(f'remainder of b/9 = remainder of {b}/9 = {b%9}')

(Modulo returns the remainder of dividing the left hand operand by right hand operand)
remainder of b/9 = remainder of 4/9 = 4


In [18]:
# Works for strings
a = 'hello'
b = 'world'
c = 'Hello'
print('a==b: ' + str(a==b))
print('a==c: ' + str(a==c))
print('a!=b: ' + str(a!=b))
print()

a==b: False
a==c: False
a!=b: True



In [19]:
# Works for numeric
d = 5
e = 8
print('d < e: ' + str(d < e))
print('d >= e: ' + str(d >= e))

d < e: True
d >= e: False


In [20]:
n = 2

if n:
    print("n is non-0 or not None")

n is non-0 or not None


In [21]:
if n is None:
    print("n is None")
    
if n is not str:
    print("n is not string")

n is not string


In [22]:
x = 20
y = 21

if y > x:
    print('y > x')
elif y < x:
    print('y < x')

y > x


In [23]:
if x==20 and y==21:
    print('True')
else:
    print('False')

True


In [24]:
if x==20 or y==100:
    print('True')
else:
    print('False')

True


In [25]:
if x==200 or y==100:
    print('True')
else:
    print('False')

False


In [26]:
x = 0
end = 10

csum = 0
while x < end:
    csum += x
    print(x, csum)
    x += 1
print("Exited with x==%d" % x )

0 0
1 1
2 3
3 6
4 10
5 15
6 21
7 28
8 36
9 45
Exited with x==10


In [27]:
list_a = [1,2,3]
print(list_a)

[1, 2, 3]


In [28]:
list_of_strings = ['hello', 'bye', 'hi']
print(list_of_strings)

['hello', 'bye', 'hi']


In [29]:
# Indexing and Slicing
list_b = ['list','of','things']
print(list_b[0])
print(list_b[1:3])

list
['of', 'things']


In [30]:
list = [1,2,3,4,5]
list[0::2]

[1, 3, 5]

In [31]:
# List methods (insert)
list_b.insert(2,'python')
print(list_b)

['list', 'of', 'python', 'things']


In [32]:
# List methods (append)
list_b.append('.')
print(list_b)

['list', 'of', 'python', 'things', '.']


In [33]:
# Methods could be applied to other objects (like strings)
example_string = 'PSYC 347 - Computational Models of Human Social Behavior and Neuroscience'
print(example_string)
print(example_string.upper())

PSYC 347 - Computational Models of Human Social Behavior and Neuroscience
PSYC 347 - COMPUTATIONAL MODELS OF HUMAN SOCIAL BEHAVIOR AND NEUROSCIENCE


In [34]:
# Dictionaries
eng2sp = {}
eng2sp['one'] = 'uno'
print(eng2sp)

{'one': 'uno'}


In [35]:
eng2sp = {'one': 'uno', 'two': 'dos', 'three': 'tres'}
print(eng2sp)

{'one': 'uno', 'two': 'dos', 'three': 'tres'}


In [36]:
# keys vs values
print(eng2sp.keys())
print(eng2sp.values())

dict_keys(['one', 'two', 'three'])
dict_values(['uno', 'dos', 'tres'])


In [37]:
for i in [0, 1, 2, 3, 4, 5]:
    print(i)

0
1
2
3
4
5


In [38]:
for i in range(6):
    print(i)

0
1
2
3
4
5


In [39]:
for i in range(2,5):
    print(i)

2
3
4


In [40]:
# indexing using for loops
list_a = ['P','S','Y','C','H']

for index, value in enumerate(list_a):
    print(index, value)

0 P
1 S
2 Y
3 C
4 H


In [41]:
example_string = "Python is making science easier"
for c in example_string:
    print(c)

P
y
t
h
o
n
 
i
s
 
m
a
k
i
n
g
 
s
c
i
e
n
c
e
 
e
a
s
i
e
r


In [42]:
# appending to lists in for loop
print(list_b)

print('\n...running for loop\n')
for value in ['a','b','c']:
    list_b.append(value)
    
print(list_b)

['list', 'of', 'python', 'things', '.']

...running for loop

['list', 'of', 'python', 'things', '.', 'a', 'b', 'c']


In [43]:
# manipulating lists using for loops
for value in ['m','o','d','e','l','s']:
    print(value.upper())

M
O
D
E
L
S


In [44]:
# only capitalize every other letter
for index, value in enumerate(['m','o','d','e','l','s']):
    if index % 2:
        print(value.upper())
    else:
        print(value)

m


O
d
E
l
S


In [45]:
# list comprehension
list_example = [10, 11, 12, 13, 14, 15]

print([x*9 for x in list_example])

[90, 99, 108, 117, 126, 135]


In [46]:
# List Comprehension with methods
list_example2 = ['words', 'to', 'change']

print([x.upper() for x in list_example2])

['WORDS', 'TO', 'CHANGE']

In [47]:
def make_upper_case(text):
    return (text.upper())

In [48]:
string = "Python is making science easier"
string_upper = string.upper()
print(string_upper)

PYTHON IS MAKING SCIENCE EASIER

In [49]:
make_upper_case(string)

'PYTHON IS MAKING SCIENCE EASIER'

In [50]:
# let's create a cat class
class Cat:

    # Initializer / Instance Attributes
    def __init__(self, name, age):
        self.name = name
        self.age = age
        self.hungry = True
        self.tired = True

    # instance method
    def description(self):
        __name_age__ = "{} is {} years old. ".format(self.name, self.age)
        
        if self.tired == True:
            __is_tired__ = "{} is tired. ".format(self.name)
        else:
            __is_tired__ = "{} is not tired. ".format(self.name)
        
        if self.hungry == True:
             __is_hungry__ = "{} is hungry. ".format(self.name)
        else:
            __is_hungry__ = "{} is not hungry. ".format(self.name)
        
        return str(__name_age__+__is_tired__+__is_hungry__)

    # instance method
    def meow(self):
        return "{} says {}".format(self.name, "Meow! Meow!")
    
    def feed(self):
        self.hungry = False
        print(self.meow())
        
    def sleep(self):
        self.tired = False

In [51]:
# Instantiate the Cat object
kitty = Cat("Fat Cat", 6)

In [52]:
# call our instance methods
print(kitty.description())
print(kitty.meow())

Fat Cat is 6 years old. Fat Cat is tired. Fat Cat is hungry. 


Fat Cat says Meow! Meow!


In [53]:
kitty.feed()

Fat Cat says Meow! Meow!


In [54]:
print(kitty.description())

Fat Cat is 6 years old. Fat Cat is tired. Fat Cat is not hungry. 


In [55]:
kitty.sleep()

In [56]:
print(kitty.description())

Fat Cat is 6 years old. Fat Cat is not tired. Fat Cat is not hungry. 


In [57]:
kitty.name = 'Shawn'

In [58]:
kitty.meow()

'Shawn says Meow! Meow!'

In [59]:
import os
from glob import glob

In [60]:
if 'google.colab' in str(get_ipython()):
    print('Running on Colab... Printing list of directories')
    data_file_list = glob('/*')
else:
    print('Not running on Colab... Printing list of files')
    data_file_list = glob(os.path.join(os.path.curdir,'*ipynb'))
print(data_file_list)

Not running on Colab... Printing list of files
['.\\module-01-00_Jupyter-Notebooks-Colab.ipynb', '.\\module-01-00_Jupyter-Notebooks.ipynb', '.\\module-01-01_Intro-to-Python.ipynb', '.\\module-01-02_Working-with-Data.ipynb', '.\\module-01-03_Python-Exercises.ipynb', '.\\module-02-00_Linear-Modeling.ipynb', '.\\module-02-01_Nonlinear-Modeling.ipynb', '.\\module-02-02_Modeling-Exercises.ipynb', '.\\module-03-00_Two-Armed-Bandit.ipynb', '.\\module-03-01_Models-of-Learning.ipynb', '.\\module-03-02_RL-Exercises.ipynb', '.\\module-04-00_Social-Learning.ipynb', '.\\module-04-01_Prosocial-RL-Exercises.ipynb']


In [61]:
file_list = []
for f in data_file_list:
    file_list.append(os.path.basename(f))

print(file_list)

['module-01-00_Jupyter-Notebooks-Colab.ipynb', 'module-01-00_Jupyter-Notebooks.ipynb', 'module-01-01_Intro-to-Python.ipynb', 'module-01-02_Working-with-Data.ipynb', 'module-01-03_Python-Exercises.ipynb', 'module-02-00_Linear-Modeling.ipynb', 'module-02-01_Nonlinear-Modeling.ipynb', 'module-02-02_Modeling-Exercises.ipynb', 'module-03-00_Two-Armed-Bandit.ipynb', 'module-03-01_Models-of-Learning.ipynb', 'module-03-02_RL-Exercises.ipynb', 'module-04-00_Social-Learning.ipynb', 'module-04-01_Prosocial-RL-Exercises.ipynb']


In [62]:
[os.path.basename(x) for x in data_file_list]

['module-01-00_Jupyter-Notebooks-Colab.ipynb',
 'module-01-00_Jupyter-Notebooks.ipynb',
 'module-01-01_Intro-to-Python.ipynb',
 'module-01-02_Working-with-Data.ipynb',
 'module-01-03_Python-Exercises.ipynb',
 'module-02-00_Linear-Modeling.ipynb',
 'module-02-01_Nonlinear-Modeling.ipynb',
 'module-02-02_Modeling-Exercises.ipynb',
 'module-03-00_Two-Armed-Bandit.ipynb',
 'module-03-01_Models-of-Learning.ipynb',
 'module-03-02_RL-Exercises.ipynb',
 'module-04-00_Social-Learning.ipynb',
 'module-04-01_Prosocial-RL-Exercises.ipynb']

In [63]:
import numpy as np

In [64]:
a = np.arange(15) #array of numbers 0 to 14
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [65]:
a.dtype

dtype('int32')

In [66]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [67]:
print(a.shape)

(15,)


In [68]:
print(a.ndim)

1


In [69]:
print(a.dtype.name)

int32


In [70]:
print(a.itemsize)

4


In [71]:
print(a.size)

15


In [72]:
print(type(a))

<class 'numpy.ndarray'>


In [73]:
b = np.array([6, 7, 8])
print(b)

[6 7 8]


In [74]:
print(type(b))

<class 'numpy.ndarray'>


In [75]:
c = np.array([(1.5, 2 ,3), (4, 5, 6), (7.1, 7.2, 7.3)])
print(c)

[[1.5 2.  3. ]
 [4.  5.  6. ]
 [7.1 7.2 7.3]]


In [76]:
print(c.shape)

(3, 3)


In [77]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [78]:
test = np.ones((2,3,4), dtype=np.int16)
print(test)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [79]:
np.random.rand(3,2)

array([[0.39949375, 0.41555926],
       [0.13288009, 0.24737957],
       [0.63990989, 0.48347466]])

In [80]:
np.empty((2,3)) # uninitialized, output may vary

array([[0.39949375, 0.41555926, 0.13288009],
       [0.24737957, 0.63990989, 0.48347466]])

In [81]:
np.arange( 10, 30, 5 ) # array from 10 to 30 in increments of 5

array([10, 15, 20, 25])

In [82]:
example = np.random.rand(4,4)
print(example)

[[0.23821239 0.28808103 0.88144708 0.02655015]
 [0.98834003 0.56144107 0.10216551 0.7278637 ]
 [0.44278863 0.22308991 0.39175518 0.53151663]
 [0.14110545 0.05314519 0.87420531 0.13068332]]


In [83]:
example*10

array([[2.38212392, 2.88081026, 8.81447078, 0.26550153],
       [9.8834003 , 5.61441068, 1.02165511, 7.27863702],
       [4.42788627, 2.23089914, 3.91755184, 5.31516631],
       [1.41105449, 0.53145193, 8.74205307, 1.30683321]])

In [84]:
example_flat = example.ravel()  # returns the array, flattened
print(example_flat)

[0.23821239 0.28808103 0.88144708 0.02655015 0.98834003 0.56144107
 0.10216551 0.7278637  0.44278863 0.22308991 0.39175518 0.53151663
 0.14110545 0.05314519 0.87420531 0.13068332]


In [85]:
example_flat.reshape(2,8) # returns the array with a modified shape 2x8

array([[0.23821239, 0.28808103, 0.88144708, 0.02655015, 0.98834003,
        0.56144107, 0.10216551, 0.7278637 ],
       [0.44278863, 0.22308991, 0.39175518, 0.53151663, 0.14110545,
        0.05314519, 0.87420531, 0.13068332]])

In [86]:
example_flat.reshape(4,4) # returns the array back to original shape

array([[0.23821239, 0.28808103, 0.88144708, 0.02655015],
       [0.98834003, 0.56144107, 0.10216551, 0.7278637 ],
       [0.44278863, 0.22308991, 0.39175518, 0.53151663],
       [0.14110545, 0.05314519, 0.87420531, 0.13068332]])

In [87]:
test = np.random.rand(2,3,6)
print(test)

[[[0.27776288 0.00188374 0.3862213  0.27332585 0.14071736 0.30358983]
  [0.92892444 0.35391117 0.69842861 0.23343584 0.57921885 0.03628221]
  [0.31532529 0.16386795 0.67974041 0.20802552 0.75192795 0.88673656]]

 [[0.12711094 0.71583129 0.53881058 0.35460552 0.32292742 0.5174832 ]
  [0.34483003 0.22906021 0.20524035 0.346236   0.77753574 0.16483261]
  [0.56369009 0.46591598 0.71523996 0.74809282 0.05903637 0.61611294]]]


In [88]:
print(test.ravel())

[0.27776288 0.00188374 0.3862213  0.27332585 0.14071736 0.30358983
 0.92892444 0.35391117 0.69842861 0.23343584 0.57921885 0.03628221
 0.31532529 0.16386795 0.67974041 0.20802552 0.75192795 0.88673656
 0.12711094 0.71583129 0.53881058 0.35460552 0.32292742 0.5174832
 0.34483003 0.22906021 0.20524035 0.346236   0.77753574 0.16483261
 0.56369009 0.46591598 0.71523996 0.74809282 0.05903637 0.61611294]


In [89]:
print(example.transpose())

[[0.23821239 0.98834003 0.44278863 0.14110545]
 [0.28808103 0.56144107 0.22308991 0.05314519]
 [0.88144708 0.10216551 0.39175518 0.87420531]
 [0.02655015 0.7278637  0.53151663 0.13068332]]


In [90]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
